<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2UM13OP" failures="1" tests="1" name="com.coverFoxTest.CoverFoxTestUsingTestNGFail" time="16.616" errors="0" timestamp="2025-04-24T21:56:16 IST" skipped="0">
  <testcase classname="com.coverFoxTest.CoverFoxTestUsingTestNGFail" name="validateCoverFoxPlansFail" time="16.616">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.coverFoxTest.CoverFoxTestUsingTestNGFail.validateCoverFoxPlansFail(CoverFoxTestUsingTestNGFail.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
    <system-out>
      <![CDATA[TC failed
TC is failed validateCoverFoxPlansFail
Taking screenshot and saving at destination C:\Users\Shubham\OneDrive\Desktop\screenshots\CoverFox2025_04_24_21_55_59.png]]>
    </system-out>
  </testcase> <!-- validateCoverFoxPlansFail -->
  <system-out>
    <![CDATA[Launching Browser
Launching Browser
Launching Browser
Launching Browser
Clicking on Gender
Clicking on Gender
Clicking on Gender
Handeling Age Dropdown
Handeling Age Dropdown
Clicking on Gender
Handeling Age Dropdown
Address details Page
Clicking continue button
Address details Page
Entering Pin
Handeling Age Dropdown
Address details Page
Entering Pin
Entering Mobile number
Entering Mobile number
Clicking continue button
Clicking continue button
Address details Page
Clicking continue button
Fetching plan number from Text
TC failed
TC is failed validateCoverFoxPlansFail
Checking if pincode error msg is displayed true
Fetching plan number from plan cards
Plan number from Text = 48
Plan number from Cards = 48
TC Passed
TC is passed validateCoverFoxPlans
Closing Browser
Checking if mobile error msg is displayed true
TC is passed validateAddressPageErrorMessages
Closing Browser
Taking screenshot and saving at destination C:\Users\Shubham\OneDrive\Desktop\screenshots\CoverFox2025_04_24_21_55_59.png
Closing Browser
Checking if mobile error msg is displayed true
TC is passed validateAddressPageMobileErrorMessages
Closing Browser
Launching Browser
Clicking on Gender
Handeling Age Dropdown
Address details Page
Clicking continue button
Checking if pincode error msg is displayed true
TC is passed validateAddressPagePinErrorMessages
Closing Browser]]>
  </system-out>
</testsuite> <!-- com.coverFoxTest.CoverFoxTestUsingTestNGFail -->
